### ISSUE TITLE
訪問web terminal後會造成延遲問題

### ISSUE THREAD

**Issue by NatLee** [NatLee/telepy#1]
如題，有一個延遲bug

復現方式：

1. 先隨意使用任一web terminal (有沒有連通沒關係)

![image](https://github.com/NatLee/telepy/assets/10178964/ad4f3c59-4456-4631-8ddb-bbd74f787078)

2. 關閉後，回到首頁測試其他API會有明顯延遲

![image](https://github.com/NatLee/telepy/assets/10178964/5c6754a7-39e1-4d6a-a89b-3ff8733c2301)

正常沒開過terminal的話，時間是這樣

![image](https://github.com/NatLee/telepy/assets/10178964/b605f285-72d6-45e6-bc53-a52dece213cc)

----

目前推測是開啟terminal的這段 Event loop 造成其他服務延遲
https://github.com/NatLee/telepy/blob/main/src/tunnels/consumers.py#L73

有待釐清QQ

**Comment by h-alice** [comment]
根據目前資料，假如直接kill writer程序，會有可能讓reader卡在無限讀出空字串的情形，這會造成event loop blocking
https://github.com/NatLee/telepy/blob/7be26cc1ac825e7c9eb99db3340861fb6ffec926/src/tunnels/consumers.py#L73

**Comment by NatLee** [comment]
已在這次commit修正 :3

https://github.com/NatLee/telepy/commit/710afdca1b41a703654707c5d6dffe8e7c67323a
