### ISSUE TITLE
"illegal group name" while executing startapp.

### ISSUE THREAD

**Issue by h-alice** [NatLee/telepy#52]
This issue occurred while executing `dev-startapp.sh` in MacBook.
So far, I think this issue is caused by `sudo chown -R $USER:$USER ./src/$@`.

<img width="482" alt="Screenshot 2024-10-13 at 2 41 46 AM" src="https://github.com/user-attachments/assets/e1098e14-ad31-4a96-9220-65085f9c7531">

**Comment by NatLee** [comment]
This is a bit convoluted because it uses the program inside the `container` to create a file directory, but it needs to be readable by the OS outside the container, so that's why `chown` is necessary.

**Comment by NatLee** [comment]
It'll be fixed in this commit https://github.com/NatLee/telepy/pull/53/commits/68b8e7faa031566db6de802ead43765795b400d8
