### ISSUE TITLE
Windows上使用powershell的問題

### ISSUE THREAD

**Issue by NatLee** [NatLee/telepy#9]
如題

當endpoint是windows機器且SSH的shell是使用powershell
endpoint端會無法讀取authorized_keys

導致只能用密碼登入

**Comment by h-alice** [comment]
# About the Issue of Logging in SSH Server for Windows with Public Key
## 症狀
- 無法使用公鑰登入SSH伺服器, 但是密碼登入可以正常運作

## TL;DR:
- SSHD的設定檔在`C:\ProgramData\ssh\sshd_config`
- 把Admin的公鑰放在`C:\ProgramData\ssh\administrators_authorized_keys`

## 觀察:
Windows上的SSH伺服器會從下列路徑讀取設定檔：
```plaintext
C:\ProgramData\ssh\sshd_config
```

從設定檔中可以看到一行關於AuthorizedKeys的設定：
```plaintext
Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

由此可見, 對於管理者有另一套公鑰的設定檔 (應該是因為安全理由, 但我不認為真的比較安全😂)

## 解決方法
如同一般的authorized_keys, 將公鑰放入`administrators_authorized_keys`, 重新啟動SSHD即可

```powershell
net stop sshd
net start sshd
```

**Comment by h-alice** [comment]
不過這牽涉到編輯`administrators_authorized_keys`或`sshd_config` 兩個都要提權
你覺得要如何處置

**Comment by NatLee** [comment]
其實還好，因為設定是在目標機器
所以理論上，目標機器會有全權限

**Comment by NatLee** [comment]
這邊實測後，已完成

並且在建立通道的時候，加入提示

https://github.com/NatLee/telepy/commit/9aa1cfafea3dbb03a06742cafc3542c584ef4c58

<img width="1240" alt="image" src="https://github.com/NatLee/telepy/assets/10178964/2ce46cd3-4ce0-48bb-a97d-4eb192252ba8">

這個issue可以close了 ：D
